const mockUsers = [
  {
    _id: "6749f5155488c7b4b060702a",
    firstName: "Samyak",
    lastName: "Shah",
    profilePicURL:
      "https://res.cloudinary.com/dwv22wqtq/image/upload/v1732985273/bar2io36gggvfwshz9e6.jpg",
    position: "Computer Science",
    company: "LJ University",
    preferredTechnologies: ["Web development"],
    socialLinks: {
      linkedIn: "kwnw",
      github: "",
      X: "",
      instagram: "",
      peerlist: "",
    },
    username: "samyakshah",
    yearsOfExperience: 0,
  },
  {
    _id: "6749f5155488c7b4b060702b",
    firstName: "John",
    lastName: "Doe",
    profilePicURL:
      "https://res.cloudinary.com/dwv22wqtq/image/upload/v1732985273/bar2io36gggvfwshz9e6.jpg",
    position: "Software Engineer",
    company: "Tech Corp",
    preferredTechnologies: ["React", "Node.js"],
    socialLinks: {
      linkedIn: "johndoe",
      github: "johndoe123",
      X: "johndoe_x",
      instagram: "johndoe_ig",
      peerlist: "",
    },
    username: "johndoe",
    yearsOfExperience: 3,
  },
  {
    _id: "6749f5155488c7b4b060702c",
    firstName: "Jane",
    lastName: "Smith",
    profilePicURL:
      "https://res.cloudinary.com/dwv22wqtq/image/upload/v1732985273/bar2io36gggvfwshz9e6.jpg",
    position: "Data Scientist",
    company: "AI Labs",
    preferredTechnologies: ["Python", "TensorFlow"],
    socialLinks: {
      linkedIn: "janesmith",
      github: "",
      X: "",
      instagram: "",
      peerlist: "",
    },
    username: "janesmith",
    yearsOfExperience: 5,
  },
  {
    _id: "6749f5155488c7b4b060702d",
    firstName: "Alice",
    lastName: "Johnson",
    profilePicURL:
      "https://res.cloudinary.com/dwv22wqtq/image/upload/v1732985273/bar2io36gggvfwshz9e6.jpg",
    position: "UX Designer",
    company: "Creative Studio",
    preferredTechnologies: ["Figma", "Adobe XD"],
    socialLinks: {
      linkedIn: "alicejohnson",
      github: "",
      X: "",
      instagram: "alice_ig",
      peerlist: "",
    },
    username: "alicejohnson",
    yearsOfExperience: 4,
  },
  {
    _id: "6749f5155488c7b4b060702e",
    firstName: "Michael",
    lastName: "Brown",
    profilePicURL:
      "https://res.cloudinary.com/dwv22wqtq/image/upload/v1732985273/bar2io36gggvfwshz9e6.jpg",
    position: "DevOps Engineer",
    company: "Cloud Systems",
    preferredTechnologies: ["AWS", "Docker"],
    socialLinks: {
      linkedIn: "michaelbrown",
      github: "michaelbrown_dev",
      X: "",
      instagram: "",
      peerlist: "",
    },
    username: "michaelbrown",
    yearsOfExperience: 6,
  },
  {
    _id: "6749f5155488c7b4b060702f",
    firstName: "Sarah",
    lastName: "Williams",
    profilePicURL:
      "https://res.cloudinary.com/dwv22wqtq/image/upload/v1732985273/bar2io36gggvfwshz9e6.jpg",
    position: "Product Manager",
    company: "Innovate Inc.",
    preferredTechnologies: ["Agile", "Scrum"],
    socialLinks: {
      linkedIn: "sarahwilliams",
      github: "",
      X: "sarah_x",
      instagram: "",
      peerlist: "",
    },
    username: "sarahwilliams",
    yearsOfExperience: 7,
  },
  {
    _id: "6749f5155488c7b4b0607030",
    firstName: "David",
    lastName: "Lee",
    profilePicURL:
      "https://res.cloudinary.com/dwv22wqtq/image/upload/v1732985273/bar2io36gggvfwshz9e6.jpg",
    position: "Backend Developer",
    company: "API Solutions",
    preferredTechnologies: ["Node.js", "MongoDB"],
    socialLinks: {
      linkedIn: "davidlee",
      github: "davidlee_dev",
      X: "",
      instagram: "",
      peerlist: "",
    },
    username: "davidlee",
    yearsOfExperience: 5,
  },
  {
    _id: "6749f5155488c7b4b0607031",
    firstName: "Emily",
    lastName: "Davis",
    profilePicURL:
      "https://res.cloudinary.com/dwv22wqtq/image/upload/v1732985273/bar2io36gggvfwshz9e6.jpg",
    position: "Frontend Developer",
    company: "UI Wizards",
    preferredTechnologies: ["Vue.js", "CSS"],
    socialLinks: {
      linkedIn: "emilydavis",
      github: "",
      X: "",
      instagram: "",
      peerlist: "",
    },
    username: "emilydavis",
    yearsOfExperience: 4,
  },
  {
    _id: "6749f5155488c7b4b0607032",
    firstName: "Robert",
    lastName: "Garcia",
    profilePicURL:
      "https://res.cloudinary.com/dwv22wqtq/image/upload/v1732985273/bar2io36gggvfwshz9e6.jpg",
    position: "Security Analyst",
    company: "CyberSecure",
    preferredTechnologies: ["Cybersecurity", "Penetration Testing"],
    socialLinks: {
      linkedIn: "robertgarcia",
      github: "",
      X: "",
      instagram: "",
      peerlist: "",
    },
    username: "robertgarcia",
    yearsOfExperience: 8,
  },
  {
    _id: "6749f5155488c7b4b0607033",
    firstName: "Sophia",
    lastName: "Miller",
    profilePicURL:
      "https://res.cloudinary.com/dwv22wqtq/image/upload/v1732985273/bar2io36gggvfwshz9e6.jpg",
    position: "Machine Learning Engineer",
    company: "AI Innovators",
    preferredTechnologies: ["PyTorch", "Scikit-learn"],
    socialLinks: {
      linkedIn: "sophiamiller",
      github: "",
      X: "",
      instagram: "",
      peerlist: "",
    },
    username: "sophiamiller",
    yearsOfExperience: 5,
  },
];

export { mockUsers };
